
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Takhnoussa
 */






public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radiocap = new javax.swing.JRadioButton();
        radiocoffee = new javax.swing.JRadioButton();
        radiotea = new javax.swing.JRadioButton();
        radioiced = new javax.swing.JRadioButton();
        checkcrepe = new javax.swing.JCheckBox();
        checkgazouz = new javax.swing.JCheckBox();
        checkpizza = new javax.swing.JCheckBox();
        checksal = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtext = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taxtext = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        totaltext = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnent = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coffee La casa del gelato");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        radiocap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radiocap.setText("Cappuccino  3.5DT");
        radiocap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocapActionPerformed(evt);
            }
        });

        radiocoffee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radiocoffee.setText("Coffe 4.5DT");
        radiocoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocoffeeActionPerformed(evt);
            }
        });

        radiotea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radiotea.setText("Tea  2DT");
        radiotea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioteaActionPerformed(evt);
            }
        });

        radioiced.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioiced.setText("Iced Coffee    9.8DT");
        radioiced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioicedActionPerformed(evt);
            }
        });

        checkcrepe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkcrepe.setText("Crepe 10 DT");

        checkgazouz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkgazouz.setText("Gazouz  3.5DT");
        checkgazouz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkgazouzActionPerformed(evt);
            }
        });

        checkpizza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkpizza.setText("Pizza  16DT");
        checkpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpizzaActionPerformed(evt);
            }
        });

        checksal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checksal.setText("Salé  13DT");
        checksal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checksalActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(subtext);

        jScrollPane2.setViewportView(taxtext);

        jScrollPane3.setViewportView(totaltext);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Subtotal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tax");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Total");

        btnent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnent.setText("Enter");
        btnent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasse_coffe.gif"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(radiocoffee)
                                    .addGap(471, 471, 471)
                                    .addComponent(checkgazouz))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiocap)
                                    .addComponent(radiotea, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioiced, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checksal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkpizza)
                                    .addComponent(checkcrepe))
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(btnent)
                        .addGap(38, 38, 38)
                        .addComponent(btnclear)
                        .addGap(32, 32, 32)
                        .addComponent(btnexit)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(367, 367, 367))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiocoffee)
                    .addComponent(checkgazouz))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiocap)
                    .addComponent(checkcrepe))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiotea)
                    .addComponent(checkpizza))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioiced)
                            .addComponent(checksal))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnent)
                    .addComponent(btnclear)
                    .addComponent(btnexit))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiocapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocapActionPerformed
        // TODO add your handling code here:
          if (radiocap.isSelected())
            radiocoffee.setSelected(false);
        radiotea.setSelected(false);
        radioiced.setSelected(false);
    }//GEN-LAST:event_radiocapActionPerformed

    private void radiocoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocoffeeActionPerformed
        // select coffe option 
        if (radiocoffee.isSelected())
            radiocap.setSelected(false);
        radiotea.setSelected(false);
        radioiced.setSelected(false);
            
    }//GEN-LAST:event_radiocoffeeActionPerformed

    private void radioteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioteaActionPerformed
        // TODO add your handling code here:
          if (radiotea.isSelected())
            radiocap.setSelected(false);
        radiocoffee.setSelected(false);
        radioiced.setSelected(false);
    }//GEN-LAST:event_radioteaActionPerformed

    private void checkgazouzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkgazouzActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkgazouzActionPerformed

    private void checkpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkpizzaActionPerformed

    private void checksalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checksalActionPerformed

    private void radioicedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioicedActionPerformed
        // TODO add your handling code here:
          if (radioiced.isSelected())
            radiocap.setSelected(false);
        radiotea.setSelected(false);
        radiocoffee.setSelected(false);
    }//GEN-LAST:event_radioicedActionPerformed

    private void btnentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        double total;
        double subtotal =0;
        final double TEXTRATE=.08;
        double tax;
        
                if (radiocoffee.isSelected()){
                    subtotal=subtotal+4.5;
                   
                }else if(radiocap.isSelected()){
                    subtotal=subtotal+3.5;
                }else if(radioiced.isSelected()){
                 subtotal=subtotal+9.8;   
                } else if (radiotea.isSelected()){
                    subtotal=subtotal+2;
                }
                if (checkcrepe.isSelected()){
                   subtotal=subtotal+10;
                }if(checkgazouz.isSelected()){
                   subtotal=subtotal+3.5;
                }if (checksal.isSelected()){
                   subtotal=subtotal+13;
                }
                if(checkpizza.isSelected()){
                   subtotal=subtotal+16;
                }
                subtext.setText(Double.toString(subtotal));
                subtotal =Double.parseDouble(subtext.getText());
                tax= subtotal+TEXTRATE;
                total = tax+subtotal;
                taxtext.setText(Double.toString(tax));
                totaltext.setText(Double.toString(total));
                taxtext.setText(df.format(tax));
                totaltext.setText(df.format(total));
               subtext.setText(df.format(subtotal));
                     
    }//GEN-LAST:event_btnentActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        radioiced.setSelected(false);
            radiocap.setSelected(false);
            
        radiotea.setSelected(false);
        
        radiocoffee.setSelected(false);
         checkcrepe.setSelected(false);
           
               checkgazouz.setSelected(false);
                  
               checksal.setSelected(false);
                   
               checkpizza.setSelected(false);
        totaltext.setText("");
        taxtext.setText("");
        subtext.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnent;
    private javax.swing.JButton btnexit;
    private javax.swing.JCheckBox checkcrepe;
    private javax.swing.JCheckBox checkgazouz;
    private javax.swing.JCheckBox checkpizza;
    private javax.swing.JCheckBox checksal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radiocap;
    private javax.swing.JRadioButton radiocoffee;
    private javax.swing.JRadioButton radioiced;
    private javax.swing.JRadioButton radiotea;
    private javax.swing.JTextPane subtext;
    private javax.swing.JTextPane taxtext;
    private javax.swing.JTextPane totaltext;
    // End of variables declaration//GEN-END:variables
}
